### ISSUE TITLE
SetupConnectiions er

### ISSUE THREAD

**Issue by Alexey-T** [mtxr/CudaText-SQLTools#11]
(no info)
TypeError: must be str, not None

This is after prev bugreport (when error was shown)
After Cud restart- it works

**Comment by Alexey-T** [comment]
I tested not Ok, close

**Comment by Alexey-T** [comment]
this and #10 reason: Not called on_start, coz InstallFromGithub used. 
If u move initializing to `__init__` then will be ok with InstallFromGH

**Comment by mtxr** [comment]
sure. Sorry, I was not testing install from github function, but on_start is working.

Plugin should be able to load default connection for auto complete (future)

**Comment by Alexey-T** [comment]
for autocomplete `__init__` is ok. Install.inf needs lexers=SQL for autocomplete, then Sql autocompl will call plugin, then `__init__` works
