### ISSUE TITLE
inited 2 times, wish: no on_start

### ISSUE THREAD

**Issue by Alexey-T** [mtxr/CudaText-SQLTools#15]
```
Python 3.4.3
Setting icons: AwOken_24x24
cuda_sqltools (v0.0.1): Logging is active
cuda_sqltools (v0.0.1): Connection timeout setted to 5000 seconds
cuda_sqltools (v0.0.1): Connection history defined with max size 100
cuda_sqltools (v0.0.1): cuda_sqltools Loaded!
cuda_sqltools (v0.0.1): Logging is active
cuda_sqltools (v0.0.1): Connection timeout setted to 5000 seconds
cuda_sqltools (v0.0.1): Connection history defined with max size 100
cuda_sqltools (v0.0.1): cuda_sqltools Loaded!
```

After you debug, pls del on_start

**Comment by mtxr** [comment]
Problem is that it's not being loaded when closes and reooen.

Could you test and fix this one?

**Comment by Alexey-T** [comment]
U mean "reset plugins", it dont work after it? I see it works if
-  disable on_start (.inf)
- restart
- ctrl+E ctrl+E
- call reset-plugins
- then ctrl+E Ctrl+E

**Comment by mtxr** [comment]
No, I mean plugins hotkeys. Not working here

**Comment by Alexey-T** [comment]
After "reset plugins" ctrl+E ctrl+E dont work? it is ok here

**Comment by Alexey-T** [comment]
Pls tell what don't work after reset-plugins.. Patch: diasbled on_start

**Comment by mtxr** [comment]
sorry, i was in a hurry, I'l run some tests again and let you know. Also I'm having a lot of trouble if ST plugin and receiving a lot of emails about it :(

**Comment by Alexey-T** [comment]
It is bugs in API? Then i wait

**Comment by Alexey-T** [comment]
released SqlT for Cuda. on_start removed...
